blank_issues_enabled: true
contact_links:
  - name: 🙋🏾 Question
    url: https://github.com/feelantera/moonlight/discussions/new
    about: Use this link to submit your question to GitHub Discussions.
